spring:
  config:
    import: classpath:/env.yml
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: false

logging:
  level:
    org.springframework.core.LocalVariableTableParameterNameDiscoverer: error

jwt:
  secretKey: ${jwt.secret}
  prefix: ${jwt.prefix}
  accessTokenExp: ${jwt.access-token-exp}

oauth:
  bsm:
    client-id: ${oauth.bsm.client-id}
    client-secret: ${oauth.bsm.client-secret}